FROM python:3.6

RUN apt-get update && apt-get upgrade -y \
        && rm -rf /var/lib/apt/lists/*

COPY knative/requirements.txt requirements.txt

RUN pip install --upgrade pip setuptools six && pip install --no-cache-dir -r requirements.txt

ENV PORT 8080
ENV PYTHONUNBUFFERED TRUE

ENV APP_HOME /triggerflow
WORKDIR $APP_HOME

ADD knative/controller.py .
ADD knative/cloudant_client.py .
ADD config.yaml .

CMD exec gunicorn --bind :$PORT --workers 1 controller:app 