FROM python:3.6

RUN apt-get update && apt-get upgrade -y \
        && rm -rf /var/lib/apt/lists/*

COPY knative/requirements.txt requirements.txt

RUN pip install --upgrade pip setuptools six && pip install --no-cache-dir -r requirements.txt

ENV PORT 8080
ENV PYTHONUNBUFFERED TRUE

ENV APP_HOME /triggerflow
WORKDIR $APP_HOME

ADD knative/controllerproxy.py .
ADD eventprocessor/libs/cloudant_client.py .
ADD config.yaml .

CMD exec gunicorn --workers 1 --worker-class eventlet --bind :$PORT controllerproxy:app 